# Lab | Data Cleaning and Formatting

In this lab, we will work with customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

Para garantizar la coherencia y la facilidad de uso, estandarice los nombres de las columnas del marco de datos. Comience echando un primer vistazo al marco de datos e identificando los nombres de las columnas que deban modificarse. Utilice convenciones de nomenclatura adecuadas y asegúrese de que los nombres de las columnas sean descriptivos e informativos.

*Pista*:
- *Los nombres de las columnas deben estar en minúsculas*
- *Los espacios en blanco en los nombres de las columnas deben reemplazarse por `_`*
- *`st` podría reemplazarse por `state`*

In [157]:
import pandas as pd

In [158]:
url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'
df_clientes = pd.read_csv(url)

In [159]:
df_clientes.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [160]:
df_clientes.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

In [161]:
df_clientes.columns = df_clientes.columns.str.lower().str.replace(" ", "_")
df_clientes = df_clientes.rename(columns= {'st': 'state'})

In [162]:
df_clientes.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

## Exercise 2: Cleaning invalid Values

El conjunto de datos contiene columnas con valores inconsistentes e incorrectos que podrían afectar la precisión de nuestro análisis. Por lo tanto, debemos limpiar estas columnas para asegurarnos de que solo contengan datos válidos.

Tenga en cuenta que este ejercicio se centrará únicamente en limpiar valores inconsistentes y no implicará el manejo de valores nulos (NaN o Ninguno).

*Pista*:
- *La columna Género contiene varios valores inconsistentes, como "F", "M", "Femal", "Male", "female", que deben estandarizarse, por ejemplo, a "M" y "F".*
- *Las abreviaturas del estado se pueden reemplazar con su nombre completo, por ejemplo "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *En educación, "Bachelors" podría reemplazarse por "Bachelor"*
- *En Valor de vida del cliente, elimine el carácter `%`*
- *En la clase de vehículo, "Sports Car", "Luxury SUV" y "Luxury Car" podrían sustituirse por "Luxury"*

In [163]:
df_clientes['gender'] = df_clientes['gender'].str.strip().str.lower()
df_clientes.loc[df_clientes['gender'].str.startswith('f', na=False), 'gender'] = 'F'
df_clientes.loc[df_clientes['gender'].str.startswith('m', na=False), 'gender'] = 'M'

In [164]:
estados = {"AZ": "Arizona", "Cali": "California", "WA": "Washington"}
df_clientes['state'] = df_clientes['state'].str.strip().replace(estados)

In [165]:
df_clientes['education'] = df_clientes['education'].str.strip().replace('Bachelors', 'Bachelor')

In [166]:
df_clientes["customer_lifetime_value"] = (df_clientes["customer_lifetime_value"].str.replace("%", "", regex=False).astype(float))

In [167]:
df_clientes['vehicle_class'] = df_clientes['vehicle_class'].str.strip().replace(["Sports Car", "Luxury SUV", "Luxury Car"], 'Luxury')

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value must be numerical*
- *Number of open complaints has incorrect format. Look at the different values ​​you take with `unique()` and take the middle value. As an example, 5/1/00 should be 5. The number of open complaints is a string; remember you can use `split()` to handle it and take the number you need. Finally, since it must be numeric, cast the column to have the appropriate type.*

In [168]:
df_clientes['number_of_open_complaints'].unique()

<ArrowStringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

In [171]:
df_clientes["number_of_open_complaints"] = (df_clientes["number_of_open_complaints"].str.split("/").str[0].astype("Int64"))

In [172]:
df_clientes.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1,Personal Auto,Four-Door Car,17.269323

In [173]:
df_clientes['number_of_open_complaints'].unique()

<IntegerArray>
[1, <NA>]
Length: 2, dtype: Int64

## Exercise 4: Dealing with Null values

Identify columns with null or missing values. Identify how many null values ​​each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling null values. There are several options, including:

- Drop rows or columns with null values
- Fill in null values with a specific value (such as the column mean or median for numeric variables and the mode for categorical variables)
- Fill null values with the previous or next value in the column
- Fill in null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy for handling null values. You can use the `fillna()` function in pandas to fill null values ​​or the `dropna()` function to remove null values.

Verify that your strategy has successfully handled null values. You can use the `isnull()` function again to check if there are still null values ​​in the data set.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting the data types, as a last step, convert all numeric variables to integers.

In [174]:
df_clientes.shape

(4008, 11)

In [175]:
df_clientes.isnull().sum()
#todas las columnas tienen null y son casi la tercera parte del valor total de valores, asi que usare mean y  moda para unificarlos

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [176]:
null_cols = df_clientes.columns[df_clientes.isnull().any()]
print(null_cols)

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')

In [182]:
df_clientes.describe()
df_clientes.describe().round(2)

,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount
count,4008.00,4008.00,4008.00,4008.0,4008.00
mean,793690.26,39295.70,193.23,1.0,404.99
std,332052.32,15745.14,827.42,0.0,151.42
min,200435.07,0.00,61.00,1.0,0.38
25%,793690.26,39295.70,145.75,1.0,404.99
50%,793690.26,39295.70,193.23,1.0,404.99
75%,793690.26,39295.70,193.23,1.0,404.99
max,5816655.35,99960.00,35354.00,1.0,2893.24

In [183]:
means = df_clientes[['income','customer_lifetime_value', 'monthly_premium_auto', 'total_claim_amount']].mean()

In [184]:
df_clientes['income'] = (df_clientes['income'].fillna(df_clientes['income'].mean()))
df_clientes['customer_lifetime_value'] = (df_clientes['customer_lifetime_value'].fillna(df_clientes['customer_lifetime_value'].mean()))
df_clientes['monthly_premium_auto'] = (df_clientes['monthly_premium_auto'].fillna(df_clientes['monthly_premium_auto'].mean()))
df_clientes['total_claim_amount'] = (df_clientes['total_claim_amount'].fillna(df_clientes['total_claim_amount'].mean()))

In [185]:
df_clientes.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')

In [186]:
df_clientes['customer'] = df_clientes['customer'].fillna(df_clientes['customer'].mode().iloc[0])
df_clientes['state'] = df_clientes['state'].fillna(df_clientes['state'].mode().iloc[0])
df_clientes['gender'] = df_clientes['gender'].fillna(df_clientes['gender'].mode().iloc[0])
df_clientes['education'] = df_clientes['education'].fillna(df_clientes['education'].mode().iloc[0])
df_clientes['number_of_open_complaints'] = df_clientes['number_of_open_complaints'].fillna(df_clientes['number_of_open_complaints'].mode().iloc[0])
df_clientes['policy_type'] = df_clientes['policy_type'].fillna(df_clientes['policy_type'].mode().iloc[0])
df_clientes['vehicle_class'] = df_clientes['vehicle_class'].fillna(df_clientes['vehicle_class'].mode().iloc[0])

df_clientes.round(2).head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,793690.26,0.0,1000.0,1,Personal Auto,Four-Door Car,2.70
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1,Personal Auto,Four-Door Car,1131.46
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1,Personal Auto,Two-Door Car,566.47
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1,Corporate Auto,SUV,529.88
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1,Personal Auto,Four-Door Car,17.27

In [187]:
df_clientes.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [188]:
df_clientes[['income', 'customer_lifetime_value', 'monthly_premium_auto', 'total_claim_amount']] = (df_clientes[['income', 'customer_lifetime_value', 'monthly_premium_auto', 'total_claim_amount']].astype(int))
df_clientes.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,793690,0,1000,1,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,F,Bachelor,697953,0,94,1,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,F,Bachelor,1288743,48767,108,1,Personal Auto,Two-Door Car,566
3,WW63253,California,M,Bachelor,764586,0,106,1,Corporate Auto,SUV,529
4,GA49547,Washington,M,High School or Below,536307,36357,68,1,Personal Auto,Four-Door Car,17

## Exercise 5: Dealing with duplicates

Utilice el método `.duplicated()` para identificar cualquier fila duplicada en el marco de datos.

Decida una estrategia para manejar los duplicados. Las opciones incluyen:
- Eliminar todas las filas duplicadas
- Mantener solo la primera aparición de cada fila duplicada
- Mantener solo la última aparición de cada fila duplicada
- Eliminación de duplicados basados en un subconjunto de columnas
- Eliminación de duplicados basados en una columna específica

Implemente la estrategia elegida utilizando la función `drop_duplicates()`.

Verifique que su estrategia haya manejado exitosamente los duplicados comprobando si hay duplicados nuevamente usando `.duplicated()`.

Recuerde documentar su proceso y explicar su razonamiento para elegir una estrategia particular para manejar duplicados.

Guarde el conjunto de datos limpio en un nuevo archivo CSV.

*Sugerencia*: *después de eliminar duplicados, restablezca el índice para garantizar la coherencia*.

In [191]:
df_clientes.duplicated().sum()

np.int64(0)

In [192]:
#para esta limpieza, se mantendra solo la primera aparicion.
df_clientes = df_clientes.drop_duplicates(keep='first').reset_index(drop=True)

In [193]:
df_clientes.duplicated().sum()

np.int64(0)

In [194]:
df_clientes

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,793690,0,1000,1,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,F,Bachelor,697953,0,94,1,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,F,Bachelor,1288743,48767,108,1,Personal Auto,Two-Door Car,566
3,WW63253,California,M,Bachelor,764586,0,106,1,Corporate Auto,SUV,529
4,GA49547,Washington,M,High School or Below,536307,36357,68,1,Personal Auto,Four-Door Car,17
...,...,...,...,...,...,...,...,...,...,...,...
1067,VJ51327,California,F,High School or Below,2031499,63209,102,1,Personal Auto,SUV,207
1068,GS98873,Arizona,F,Bachelor,323912,16061,88,1,Personal Auto,Four-Door Car,633
1069,CW49887,California,F,Master,462680,79487,114,1,Special Auto,SUV,547
1070,MY31220,California,F,College,899704,54230,112,1,Personal Auto,Two-Door Car,537
1071,AA71604,California,F,Bachelor,793690,39295,193,1,Personal Auto,Four-Door Car,404

In [195]:
df_clientes.to_csv("df_clientes_limpio.csv", index=False)

# Bonus: Challenge 2: creating functions on a separate `py` file

Coloque todos los pasos de limpieza y formateo de datos en funciones y cree una función principal que realice toda la limpieza y formateo.

Escriba estas funciones en archivos .py separados. Al poner estos pasos en funciones, podemos hacer que el código sea más modular y más fácil de mantener.

*Sugerencia: el módulo de recarga automática es un módulo de utilidad en Python que le permite recargar módulos automáticamente en la sesión actual cuando se realizan cambios en el código fuente. Esto puede resultar útil en situaciones en las que está desarrollando código activamente y desea ver los efectos de los cambios que realiza sin tener que reiniciar constantemente el intérprete de Python o el kernel de Jupyter Notebook.*

In [ ]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

Se le ha encomendado la tarea de analizar datos para identificar áreas potenciales para mejorar la retención de clientes y la rentabilidad. Su objetivo es identificar a los clientes con un monto de reclamo de póliza alto y un valor de vida del cliente bajo.

En Pandas Lab, solo analizamos los montos elevados de reclamaciones de pólizas porque no podíamos analizar los valores bajos de vida del cliente. Si hubiéramos intentado trabajar con esa columna, no habríamos podido hacerlo porque el valor de vida del cliente no estaba limpio o no estaba en el formato adecuado. Entonces, después de limpiar y formatear los datos, ¡obtengamos más información interesante!

Instrucciones:

- Revise las estadísticas nuevamente para conocer el monto total del reclamo y el valor de vida del cliente para comprender los datos.
- Para identificar áreas potenciales para mejorar la retención de clientes y la rentabilidad, queremos centrarnos en clientes con un monto de reclamo de póliza alto y un valor de vida del cliente bajo. Considere que los clientes con un monto de reclamación de póliza alto son aquellos que se encuentran en el 25 % superior del monto total de reclamación, y los clientes con un valor de vida del cliente bajo son aquellos que se encuentran en el 25 % inferior del valor de vida del cliente. Cree un objeto Pandas DataFrame que contenga información sobre los clientes con un monto de reclamo de póliza superior al percentil 75 y un valor de vida del cliente en el percentil 25 inferior.
- Utilice métodos DataFrame para calcular estadísticas resumidas sobre montos de reclamos de pólizas altos y datos de valor de vida del cliente bajos. Para hacer esto, seleccione ambas columnas del marco de datos simultáneamente y páselo al método `.describe()`. Esto te brindará estadísticas descriptivas como media, mediana, desviación estándar, valores mínimo y máximo para ambas columnas al mismo tiempo, permitiéndote comparar y analizar sus características.

In [ ]:
df_clientes_limpio = df_clientes
df_clientes_limpio.describe().round(2)

In [ ]:
percentil_75 = df_clientes_limpio['total_claim_amount'].quantile(0.75)
percentil_25 = df_clientes_limpio['customer_lifetime_value'].quantile(0.25)

In [ ]:
df_clientes_target = df_clientes_limpio[(df_clientes_limpio['total_claim_amount'] > percentil_75) &  (df_clientes_limpio['customer_lifetime_value'] < percentil_25)].copy()

In [ ]:
df_clientes_target[['total_claim_amount', 'customer_lifetime_value']].describe().round(2)